version: 2
jobs:
   build:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run:
           name: Install Ionic deps
           command: npm install -g cordova ionic
